version: '3.8'

services:
  postgres:
    container_name: ignite-nest
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ignite-nest
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres
